# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensor/

homeassistant:
  external_url: !secret external_url

rest_command:
  vmix_cam_command:
    url: "http://172.16.1.1:8088/?shortcut=0fde578a-508a-4419-9ee9-97700d93cbb8"
    username: !secret vmix_username
    password: !secret vmix_password
  vmix_mon_command:
    url: "http://172.16.1.1:8088/?shortcut=089d867f-6c6e-411b-9d38-0e4f08988ab9"
    username: !secret vmix_username
    password: !secret vmix_password
  vmix_mon_cam_command:
    url: "http://172.16.1.1:8088/?shortcut=7f11e7bf-222c-4f4b-a1c8-3218e84cca77"
    username: !secret vmix_username
    password: !secret vmix_password
  vmix_cam_mon_command:
    url: "http://172.16.1.1:8088/?shortcut=3ba0aa7e-9ab3-409d-8661-c5b23b9a2cc9"
    username: !secret vmix_username
    password: !secret vmix_password
  cam_pos_1_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&1"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_2_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&2"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_3_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&3"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_4_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&4"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_5_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&5"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_6_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&6"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_7_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&7"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_8_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&8"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password
  cam_pos_9_command:
    method: GET
    url: "http://172.16.0.9/cgi-bin/ptzctrl.cgi?ptzcmd&poscall&9"
    authentication: digest
    username: !secret camera_username
    password: !secret camera_password

# ingress:
#   camera:
#     require_admin: true
#     work_mode: ingress
#     ui_mode: normal
#     title: Camera
#     icon: mdi:network
#     url: http://172.16.0.9/
#     headers:
#       http-auth-user: !secret camera_username
#       http-auth-pass: !secret camera_password
# companion:
#   work_mode: ingress
#   ui_mode: normal
#   title: Companion
#   icon: mdi:button-pointer
#   url: http://172.16.1.1:8888
#   index: /emulator/emulator
#   rewrite:
#     - mode: body
#       match: (\/assets\/index-.*\.(js|css))
#       replace: $http_x_ingress_path\1

camera:
  - platform: ffmpeg
    name: vmix
    input: srt://172.16.1.1:10000

evohome:
  username: !secret evohome_username
  password: !secret evohome_password

panel_custom:
  - name: Supervisor
    url_path: hassio/system
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js

input_select:
  trandelion:
    name: Trandelion
    options:
      - Enable
      - Disable
      - Disabled
      - Enabled
    initial: Disabled
    icon: mdi:translate

template:
  - binary_sensor:
      - default_entity_id: binary_sensor.ptz_camera_state
        name: PTZ Camera status
        state: >-
          {% if is_state("sensor.ptz_standby_state", "1") %}
            Standby
          {% else %}
            Geactiveerd
          {% endif %}
        icon: >-
          {% if is_state("sensor.ptz_standby_state", "1") %}
            mdi:cctv-off
          {% else %}
            mdi:cctv
          {% endif %}

  - switch:
      - turn_on:
          - action: input_select.select_option
            target:
              entity_id:
                - input_select.trandelion
            data:
              option: Enable
        turn_off:
          - action: input_select.select_option
            target:
              entity_id:
                - input_select.trandelion
            data:
              option: Disable
        default_entity_id: switch.trandelion
        name: Trandelion
        state: "{{ is_state('input_select.trandelion', 'Enabled') }}"

  - sensor:
      - name: "WAN Down Throughput"
        unique_id: wan_down_throughput
        unit_of_measurement: Mbps
        icon: mdi:cloud-download
        # Convert throughput derivative from Bps to Mbps
        state: "{{ ((states('sensor.network_wan_down_throughput_bps') | int) * 8 / 10**6) | round(2) }}"
        state_class: measurement

      - name: "WAN Down Usage"
        unique_id: wan_down_usage
        unit_of_measurement: GiB
        icon: mdi:cloud-download
        # Convert usage meter below from B to GiB
        state: "{{ ((states('sensor.network_wan_down_data_usage_meter_bytes') | int) / 2**30) | round(2) }}"
        state_class: total_increasing

      - name: "WAN Up Throughput"
        unique_id: wan_up_throughput
        unit_of_measurement: Mbps
        icon: mdi:cloud-upload
        # Convert throughput derivative from Bps to Mbps
        state: "{{ ((states('sensor.network_wan_up_throughput_bps') | int) * 8 / 10**6) | round(2) }}"
        state_class: measurement

      - name: "WAN Up Usage"
        unique_id: wan_up_usage
        unit_of_measurement: GiB
        icon: mdi:cloud-upload
        # Convert usage meter below from B to GiB
        state: "{{ ((states('sensor.network_wan_up_data_usage_meter_bytes') | int) / 2**30) | round(2) }}"
        state_class: total_increasing

utility_meter:
  network_wan_down_data_usage_meter_bytes:
    unique_id: network_wan_down_data_usage_meter_bytes
    name: Network - WAN Down Data Usage Meter - Bytes
    source: sensor.wan_interface_down_octets
    cycle: monthly
    offset:
      hours: 72
      minutes: 0
      seconds: 0
  network_wan_up_data_usage_meter_bytes:
    unique_id: network_wan_up_data_usage_meter_bytes
    name: Network - WAN Up Data Usage Meter - Bytes
    source: sensor.wan_interface_up_octets
    cycle: monthly
    offset:
      hours: 72
      minutes: 0
      seconds: 0

google_assistant: !include google_assistant_integ.yaml

auth_oidc:
  client_id: !secret auth_oidc_client_id
  discovery_url: !secret auth_oidc_discovery_url
  client_secret: !secret auth_oidc_client_secret
  features:
    include_groups_scope: False
